services:
  php:
    build:
      dockerfile: php/Dockerfile
    container_name: symfony_php
    volumes:
      - ../back:/var/www/html
    working_dir: /var/www/html
    networks:
      - symfony_net
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: symfony_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - symfony_net
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../back:/var/www/html
    ports:
      - "8080:80"
    networks:
      - symfony_net
    depends_on:
      - php

  node:
    build:
      dockerfile: node/Dockerfile
    container_name: symfony_node
    volumes:
      - ../front:/var/www/front
    working_dir: /var/www/front
    networks:
      - symfony_net
    ports:
      - "5173:5173"

networks:
  symfony_net:
    driver: bridge

volumes:
  postgres_data: